const List<String> departments = [
  'Accounting & Finance',
  'Administration & Management',
  'Agriculture & Agribusiness',
  'Architecture & Planning',
  'Arts & Culture',
  'Beauty & Personal Care',
  'Business & Entrepreneurship',
  'Construction & Building',
  'Education & Training',
  'Engineering',
  'Entertainment',
  'Environment & Natural Resources',
  'Fashion & Design',
  'Food & Hospitality',
  'Government & Public Administration',
  'Healthcare & Medicine',
  'Human Resources',
  'Information Technology',
  'Legal Services',
  'Manufacturing',
  'Marketing & Advertising',
  'Media & Communications',
  'Nonprofit & Community Services',
  'Politics & Public Affairs',
  'Real Estate & Property',
  'Research & Science',
  'Sales & Customer Service',
  'Security & Safety',
  'Sports & Fitness',
  'Transport & Logistics',
  'Travel & Tourism',
  'Writing & Publishing',
  'Other',
];