const List<String> industries = [
  'Agriculture & Agribusiness',
  'Arts, Culture & Entertainment',
  'Automotive & Transport',
  'Banking & Financial Services',
  'Beauty & Personal Care',
  'Construction & Real Estate',
  'Consulting & Professional Services',
  'Education & Training',
  'Energy & Utilities',
  'Engineering & Manufacturing',
  'Environment & Conservation',
  'Fashion & Textiles',
  'Food & Beverage',
  'Government & Public Administration',
  'Healthcare & Medical Services',
  'Hospitality & Tourism',
  'Human Resources & Recruitment',
  'Information Technology & Software',
  'Insurance',
  'Legal Services',
  'Logistics & Supply Chain',
  'Media, Film & Broadcasting',
  'Mining & Natural Resources',
  'Nonprofit & Charity',
  'Politics & Public Affairs',
  'Book Industry',
  'Retail & Wholesale Trade',
  'Science & Research',
  'Security & Safety',
  'Sports & Recreation',
  'Telecommunications',
  'Marketing & Advertising',
  'Community & Social Services',
  'Property Management',
  'Religious Organizations',
  'Waste Management & Recycling',
  'Other',
];
